### ISSUE TITLE
install2.sh error

### ISSUE THREAD

**Issue by PoisonNinja** [CodeBuds/Cri#4]
Running the second part of the install script gives these errors:

``` Shell
stdin: is not a tty
stdin: is not a tty
stdin: is not a tty
stdin: is not a tty
-su: 1: runner: not found
```

I'm not sure if the script completes successfully. It continues past, but there is no change in my configuration. 
stdin: is not a tty can be solved by replacing 'mesg n' with 'tty -s && mesg n' in /root/.profile

**Comment by PoisonNinja** [comment]
What is runner?

**Comment by eliliam** [comment]
Runner is the command to run things on the Ubuntu side, just let it happen

**Comment by PoisonNinja** [comment]
I got it resolved. I forked your repository and modified install2.sh to point to my SD card install of Crouton. Somehow it launched crouton, but it was using the wrong path.

**Comment by smerkousdavid** [comment]
Next time you could symlink your sd-card to /mnt/stateful-partition/crouton/chroots/precise. To make things easier

**Comment by eliliam** [comment]
And also remember to symlink where you're crouton is stored to your
/usr/local/chroots/ folder

**Comment by PoisonNinja** [comment]
My chroot is symlinked into /usr/local/chroot. I will symlink my chroot to /mnt/stateful-partition/crouton and see how it goes.

**Comment by eliliam** [comment]
Do this:
Sudo ln -s /mnt_statefulpartitions/crouton/chroots /usr/local/chroots
